### PR TITLE
pushing version 0.33

### PR DESCRIPTION
**Pull request by phaus**

### CODE REVIEW

**Comment by phaus** [comment]
@jamesward can you merge, if you have free minute? thx a lot!

**Comment by jamesward** [comment]
Maven does the actual release (removing the `-SNAPSHOT`) so no need for a PR.  I'm releasing this now.

**Comment by phaus** [comment]
So how can I have version 0.33 released to the global maven repo then?

**Comment by jamesward** [comment]
It should be there. I released it 2 days ago.

**Pull request closed without merging**
